function exportSinglePageReport(this, outputFile, varargin)
% EXPORTSINGLEPAGEREPORT Generate a single-page PDF report for participants
%   exportSinglePageReport(obj, outputFile) generates a PDF report at the specified path.
%   Optional name-value pairs:
%       'ID'         - Subject ID (string, default '')
%       'Filename'   - Original filename (string, default '')
%
%   Requires Report Generator toolbox.
%
%   Assumes all analyses (gap, sleep, nonparametric, cosinor) have been performed.
%   Plots are generated temporarily and included as images.
%
%   Report path should not be in any cloud storage otherwise there will be
%       a close error.
%
% $Author:  Peng Li
% $Date:    Feb 26, 2026
%

p = inputParser;
addParameter(p, 'ID', '', @ischar);
addParameter(p, 'Filename', '', @ischar);
parse(p, varargin{:});

subjectID = p.Results.ID;
origFilename = p.Results.Filename;

if isempty(outputFile)
    outputFile = fullfile('C:\Users\pl806\Documents', 'actigraphy_single_page_report.pdf');
end

import mlreportgen.dom.*;

doc = Document(outputFile, 'pdf');
open(doc);

% Margins
doc.CurrentPageLayout.PageMargins.Top    = '0.35in';
doc.CurrentPageLayout.PageMargins.Bottom = '0.45in';
doc.CurrentPageLayout.PageMargins.Left   = '0.45in';
doc.CurrentPageLayout.PageMargins.Right  = '0.45in';

tempFiles = {};

try
    % Footer
    footer = PDFPageFooter();
    disc = Paragraph('This report is for research purposes only and is not intended for diagnostic or clinical use. Generated by ezActi — Laboratory for Sleep and Digital Health.');
    disc.Italic = true;
    disc.FontSize = '7.5pt';
    disc.HAlign = 'center';
    append(footer, disc);
    doc.CurrentPageLayout.PageFooters = footer;

    % Title block
    titleP = Paragraph('Actigraphy Report');
    titleP.Bold = true;
    titleP.FontSize = '16pt';
    titleP.HAlign = 'center';
    append(doc, titleP);

    if ~isempty(subjectID)
        idP = Paragraph(['Subject ID: ' subjectID]);
        idP.FontSize = '10pt';
        idP.HAlign = 'center';
        append(doc, idP);
    end
    if ~isempty(origFilename)
        fnP = Paragraph(['File: ' origFilename]);
        fnP.FontSize = '9pt';
        fnP.HAlign = 'center';
        append(doc, fnP);
    end

    append(doc, Paragraph(' '));

    % ROW 1: Actigraphy + Gap
    row1 = Table(2);
    row1.Style = {Width('100%'), Border('none'), RowSep('none')};
    row1.TableEntriesStyle = {VAlign('top')};

    cg1 = TableColSpecGroup;
    c1 = TableColSpec; c1.Style = {Width('77%')};
    c2 = TableColSpec; c2.Style = {Width('23%')};
    cg1.ColSpecs = [c1 c2];
    row1.ColSpecGroups = cg1;

    h = this.plot;
    tempActi = [tempname '.svg'];
    exportgraphics(h.actigraphyFig, tempActi, 'ContentType', 'vector');
    close(h.actigraphyFig);
    imgActi = Image(tempActi);
    imgActi.Style = {Height('2.6in'), ScaleToFit(true)};
    entryActi = TableEntry;
    append(entryActi, imgActi);
    tempFiles{end+1} = tempActi;

    gapEntry = TableEntry;
    gapTitle = Text('Gap Summary');
    gapTitle.Bold = true;
    gapTitle.FontSize = '10pt';
    append(gapEntry, gapTitle);
    if ~isempty(this.GapSummary)
        human = {'Total Duration (h)', 'Non-wear Time (h)', 'Non-wear (%)'};
        vals = round(table2array(this.GapSummary), 2);
        tblGap = Table(2);
        tblGap.Style = {Width('100%'), FontSize('7pt'), Border('solid'), OuterMargin('0pt'), InnerMargin('0pt')};
        tblGap.TableEntriesStyle = {FontSize('7pt'), VAlign('middle'), LineSpacing('0.8')};
        for i = 1:length(human)
            row = TableRow;
            row.Style = {Height('0.18in')};  % force tight row height
            append(row, TableEntry(Text(human{i})));
            append(row, TableEntry(Text(num2str(vals(i)))));
            append(tblGap, row);
        end
        append(gapEntry, tblGap);
    else
        noGap = Text('No gap summary');
        noGap.FontSize = '8pt';
        append(gapEntry, noGap);
    end

    r1 = TableRow;
    r1.Height = '2.9in';
    append(r1, entryActi);
    append(r1, gapEntry);
    append(row1, r1);
    append(doc, row1);
    append(doc, Paragraph(' '));

    % ROW 2: Actogram + Clock
    row2 = Table(2);
    row2.Style = {Width('100%'), Border('none'), RowSep('none')};
    row2.TableEntriesStyle = {VAlign('top')};

    cg2 = TableColSpecGroup;
    cA = TableColSpec; cA.Style = {Width('50%')};
    cB = TableColSpec; cB.Style = {Width('50%')};
    cg2.ColSpecs = [cA cB];
    row2.ColSpecGroups = cg2;

    h = this.plotActogram;
    tempActo = [tempname '.svg'];
    exportgraphics(h.actigraphyFig, tempActo, 'ContentType', 'vector');
    close(h.actigraphyFig);
    imgActo = Image(tempActo);
    imgActo.Style = {Height('2.5in'), ScaleToFit(true)};
    entryActo = TableEntry;
    append(entryActo, imgActo);
    tempFiles{end+1} = tempActo;

    hf = figure('Color','w','Visible','off');
    ha = axes(hf, 'Units','normalized','Position',[0.1 0.1 0.8 0.8]);
    this.CosinorInfo.UserData.plot(ha);
    tempClock = [tempname '.svg'];
    exportgraphics(hf, tempClock, 'ContentType', 'vector');
    close(hf);
    imgClock = Image(tempClock);
    imgClock.Style = {Height('2.5in'), ScaleToFit(true)};
    entryClock = TableEntry;
    append(entryClock, imgClock);
    tempFiles{end+1} = tempClock;

    r2 = TableRow;
    r2.Height = '2.7in';
    append(r2, entryActo);
    append(r2, entryClock);
    append(row2, r2);
    append(doc, row2);
    append(doc, Paragraph(' '));

    % ROW 3: Four summary panels
    row3 = Table(4);
    row3.Style = {Width('100%'), Border('none'), RowSep('none'), FontSize('7pt')};
    row3.TableEntriesStyle = {VAlign('top')};

    cg3 = TableColSpecGroup;
    c1 = TableColSpec; c1.Style = {Width('25%')};
    c2 = TableColSpec; c2.Style = {Width('25%')};
    c3 = TableColSpec; c3.Style = {Width('25%')};
    c4 = TableColSpec; c4.Style = {Width('25%')};
    cg3.ColSpecs = [c1 c2 c3 c4];
    row3.ColSpecGroups = cg3;

    % Sleep Summary
    sleepE = TableEntry;
    p = Paragraph('Sleep Summary');
    p.Bold = true;
    p.FontSize = '9.5pt';
    append(sleepE, p);
    if ~isempty(this.SleepSummary.Report)
        rep = this.SleepSummary.Report;
        data = {
            'Total Sleep (h)',     num2str(round(rep.total_sleep_h,2));
            'Primary Onset',       string(rep.primary_onset, 'hh:mm:ss');
            'Primary Offset',      string(rep.primary_offset, 'hh:mm:ss');
            'Primary Sleep (h)',   num2str(round(rep.primary_sleep_h,2));
            'WASO (min)',          num2str(round(rep.waso_min,1));
            'Nap (h/day)',         num2str(round(rep.nap_h,2));
            'Nap times/day',       num2str(round(rep.nap_times,1))
            };
        tblS = Table(2);
        tblS.Style = {Width('100%'), Border('solid'), OuterMargin('0pt'), InnerMargin('0pt')};
        tblS.TableEntriesStyle = {FontSize('6.8pt'), VAlign('middle'), LineSpacing('0.8')};
        for i = 1:size(data,1)
            row = TableRow;
            row.Style = {Height('0.16in')};  % ultra-tight row height
            append(row, TableEntry(Text(data{i,1})));
            append(row, TableEntry(Text(data{i,2})));
            append(tblS, row);
        end
        append(sleepE, tblS);
    else
        p = Paragraph('No sleep data');
        p.FontSize = '8pt';
        append(sleepE, p);
    end

    % Circadian Summary
    cosE = TableEntry;
    p = Paragraph('Circadian Summary');
    p.Bold = true;
    p.FontSize = '9.5pt';
    append(cosE, p);
    if ~isempty(this.CosinorSummary)
        sum = this.CosinorSummary;
        base = {'Mean Act', 'Std Act', 'MESOR', 'MESOR LB', 'MESOR UB', 'P-val', 'R²'};
        periods = extractAfter(sum.Properties.VariableNames(contains(sum.Properties.VariableNames,'amplitude_lb_')),'amplitude_lb_');
        human = base;
        for i = 1:numel(periods)
            per = periods{i};
            human = [human {['Amp ' per], ['Amp LB ' per], ['Amp UB ' per], ['Phase ' per], ['Phase LB ' per], ['Phase UB ' per], ['Phase(h) ' per], ['Phase(h) LB ' per], ['Phase(h) UB ' per]}];
        end
        vals = round(table2array(sum),2);
        cosVals = cell(size(vals));
        cols = sum.Properties.VariableNames;
        for j = 1:length(cols)
            if contains(cols{j}, '_in_hour')
                v = vals(j);
                hh = floor(v); mm = floor((v-hh)*60); ss = round(((v-hh)*60-mm)*60);
                cosVals{j} = sprintf('%02d:%02d:%02d', hh, mm, ss);
            else
                cosVals{j} = num2str(vals(j));
            end
        end
        cosData = [human(1:length(cosVals))' cosVals'];
        tblC = Table(2);
        tblC.Style = {Width('100%'), Border('solid'), OuterMargin('0pt'), InnerMargin('0pt')};
        tblC.TableEntriesStyle = {FontSize('6.8pt'), VAlign('middle'), LineSpacing('0.8')};
        for i = 1:size(cosData,1)
            row = TableRow;
            row.Style = {Height('0.16in')};
            append(row, TableEntry(Text(cosData{i,1})));
            append(row, TableEntry(Text(cosData{i,2})));
            append(tblC, row);
        end
        append(cosE, tblC);
    else
        p = Paragraph('No cosinor data');
        p.FontSize = '8pt';
        append(cosE, p);
    end

    % IS/IV Summary
    isivE = TableEntry;
    p = Paragraph('IS/IV Summary');
    p.Bold = true;
    p.FontSize = '9.5pt';
    append(isivE, p);
    if ~isempty(this.ISIVSummary)
        human = {'IS', 'IV', 'Period (h)', '% Miss Data', '% Miss Bin', 'Timescale'};
        vals = round(table2array(this.ISIVSummary),2);
        data = [human' arrayfun(@num2str, vals', 'UniformOutput', false)];
        tblI = Table(2);
        tblI.Style = {Width('100%'), Border('solid'), OuterMargin('0pt'), InnerMargin('0pt')};
        tblI.TableEntriesStyle = {FontSize('6.8pt'), VAlign('middle'), LineSpacing('0.8')};
        for i = 1:size(data,1)
            row = TableRow;
            row.Style = {Height('0.16in')};
            append(row, TableEntry(Text(data{i,1})));
            append(row, TableEntry(Text(data{i,2})));
            append(tblI, row);
        end
        append(isivE, tblI);
    else
        p = Paragraph('No IS/IV data');
        p.FontSize = '8pt';
        append(isivE, p);
    end

    % M10/L5 Summary
    m10E = TableEntry;
    p = Paragraph('M10/L5 Summary');
    p.Bold = true;
    p.FontSize = '9.5pt';
    append(m10E, p);
    if ~isempty(this.M10L5Summary)
        human = {'RA', 'M10', 'M10 Mid (HH:mm:ss)', 'L5', 'L5 Mid (HH:mm:ss)'};
        vals = table2array(this.M10L5Summary);
        vals([1 2 4]) = round(vals([1 2 4]),2);
        m10_mid = vals(3); l5_mid = vals(5);
        m10_str = sprintf('%02d:%02d:%02d', floor(m10_mid), floor((m10_mid-floor(m10_mid))*60), round(((m10_mid-floor(m10_mid))*60 - floor((m10_mid-floor(m10_mid))*60))*60));
        l5_str  = sprintf('%02d:%02d:%02d', floor(l5_mid),  floor((l5_mid -floor(l5_mid ))*60), round(((l5_mid -floor(l5_mid ))*60 - floor((l5_mid -floor(l5_mid ))*60))*60));
        data = {
            human{1}, num2str(vals(1));
            human{2}, num2str(vals(2));
            human{3}, m10_str;
            human{4}, num2str(vals(4));
            human{5}, l5_str
            };
        tblM = Table(2);
        tblM.Style = {Width('100%'), Border('solid'), OuterMargin('0pt'), InnerMargin('0pt')};
        tblM.TableEntriesStyle = {FontSize('6.8pt'), VAlign('middle'), LineSpacing('0.8')};
        for i = 1:size(data,1)
            row = TableRow;
            row.Style = {Height('0.16in')};
            append(row, TableEntry(Text(data{i,1})));
            append(row, TableEntry(Text(data{i,2})));
            append(tblM, row);
        end
        append(m10E, tblM);
    else
        p = Paragraph('No M10/L5 data');
        p.FontSize = '8pt';
        append(m10E, p);
    end

    r3 = TableRow;
    r3.Height = '2.75in';
    append(r3, sleepE);
    append(r3, cosE);
    append(r3, isivE);
    append(r3, m10E);
    append(row3, r3);
    append(doc, row3);

    close(doc);
    disp(['Single-page report generated: ' outputFile]);

    for i = 1:length(tempFiles)
        if exist(tempFiles{i}, 'file')
            delete(tempFiles{i});
        end
    end

catch ME
    if isvalid(doc), close(doc); end
    for i = 1:length(tempFiles)
        if exist(tempFiles{i}, 'file')
            delete(tempFiles{i});
        end
    end
    rethrow(ME);
end
end