function this = exportReport(this, outputPath, varargin)
% EXPORTREPORT Generate a professional PDF report for actigraphy data
%   exportReport(obj, outputFile) generates a PDF report at the specified path.
%
%   Store to tempdir first and move to outputPath increase outputPath is
%       synced to any third-party cloud storage. There will always been a 
%       close error if so.
%
%   Optional name-value pairs:
%       'ID'         - Subject ID (string, default '')
%       'Filename'   - Original filename (string, default '')
%
%   Requires Report Generator toolbox.
%
% $Author:  Peng Li
% $Date:    Feb 26, 2026
%

p = inputParser;
addParameter(p, 'ID', '', @ischar);
addParameter(p, 'Filename', '', @ischar);
parse(p, varargin{:});

subjectID = p.Results.ID;
origFilename = p.Results.Filename;

if isempty(outputPath)
    outputPath = pwd;
end

tempPDF = fullfile(tempdir, [origFilename '_actigraphy_analysis_report.pdf']);

import mlreportgen.dom.*;
import mlreportgen.report.*;

% Create document
doc = Report(tempPDF, 'pdf');
open(doc);

tempFiles = {};

try
    %% ======================= TITLE PAGE =======================
    tp = TitlePage;
    tp.Title = 'Actigraphy Analysis Report';
    tp.Author = '';
    tp.PubDate = '';

    add(doc,tp);
    add(doc, LineBreak());
    add(doc, LineBreak());
    add(doc, LineBreak());
    add(doc, LineBreak());
    add(doc, LineBreak());

    % Subject info
    if ~isempty(subjectID)
        add(doc, Paragraph(['Subject ID: ' subjectID]));
    end
    if ~isempty(origFilename)
        add(doc, Paragraph(['File: ' origFilename]));
    end

    add(doc, LineBreak());
    add(doc, LineBreak());
    add(doc, LineBreak());
    add(doc, LineBreak());
    add(doc, LineBreak());

    % Disclosure
    pDisc = Paragraph();
    pDisc.Style = {HAlign('center'), FontSize('14pt'), Bold(true)};
    append(pDisc, Text('DISCLOSURE:'));
    add(doc, pDisc);
    pDisc = Paragraph();
    pDisc.Style = {HAlign('center'), FontSize('14pt'), Bold(true)};
    append(pDisc, Text('This report is for research purposes only'));
    add(doc, pDisc);
    pDisc = Paragraph();
    pDisc.Style = {HAlign('center'), FontSize('14pt'), Bold(true)};
    append(pDisc, Text('and is not intended for diagnostic or clinical use.'));
    add(doc, pDisc);

    add(doc, LineBreak());
    add(doc, LineBreak());
    add(doc, LineBreak());
    add(doc, LineBreak());
    add(doc, LineBreak());

    pDisc = Paragraph();
    pDisc.Style = {HAlign('right'), FontSize('10pt'), Italic(true)};
    append(pDisc, Text('Generated by ezActi - '));
    add(doc, pDisc);

    pDisc = Paragraph();
    pDisc.Style = {HAlign('right'), FontSize('10pt'), Italic(true)};
    append(pDisc, Text('A MATLAB App developed in:'));
    add(doc, pDisc);

    % Logo on title page
    logoTitle = Image(which('lsdh.png'));
    logoTitle.Style = {Height('1in'), HAlign('right')};
    add(doc, logoTitle);

    pDisc = Paragraph();
    pDisc.Style = {HAlign('right'), FontSize('10pt')};
    append(pDisc, Text('Laboratory for Sleep and Digital Health'));
    add(doc, pDisc);

    pDisc = Paragraph();
    pDisc.Style = {HAlign('right'), FontSize('10pt')};
    append(pDisc, Text('Medical Biodynamics Center'));
    add(doc, pDisc);

    pDisc = Paragraph();
    pDisc.Style = {HAlign('right'), FontSize('10pt')};
    append(pDisc, Text('Mass General Brigham | Harvard Medical School'));
    add(doc, pDisc);

    pDisc = Paragraph();
    pDisc.Style = {HAlign('right'), FontSize('10pt'), Italic(true)};
    t = Text('Visit Lab Website');
    t.Style = {Color('blue')};
    append(pDisc, ExternalLink('https://lsdh.mgh.harvard.edu', t));

    add(doc, pDisc);

    add(doc, PageBreak());

    %% ========================= CONTENT PAGES =============================
    % --- Section 1: Actigraphy Visualization ---
    sect1 = Chapter('Title', 'Wear Time and Sleep Assessment');

    % Actigraphy Plot
    add(sect1, Section('Title', 'Time-Series Plot'));
    h = this.plot('Visible', false);
    tempActi = [tempname '.svg'];
    exportgraphics(h.actigraphyFig, tempActi, 'ContentType', 'vector');
    close(h.actigraphyFig);
    img1 = FormalImage(tempActi);
    img1.Caption = Paragraph('Activity levels with identified sleep intervals and gaps.');
    img1.Caption.Bold = true; img1.Caption.FontSize = '12pt';
    add(sect1, img1);
    tempFiles{end+1} = tempActi;

    % 1. Gap Summary
    add(sect1, Section('Title', 'Gap & Wear-Time Summary'));
    if ~isempty(this.GapSummary)
        labels = {'Total Duration (h)', 'Non-wear Time (h)', 'Non-wear (%)'};
        vals = round(table2array(this.GapSummary), 2);
        data = [labels' arrayfun(@num2str, vals', 'UniformOutput', false)];
        add(sect1, createStandardTable({'Metric', 'Value'}, data));
    else
        add(sect1, 'No gap data available.');
    end

    % Actogram
    add(sect1, Section('Title', 'Actogram'));
    h = this.plotActogram('Visible', false);
    tempActo = [tempname '.svg'];
    exportgraphics(h.actigraphyFig, tempActo, 'ContentType', 'vector');
    close(h.actigraphyFig);
    img2 = FormalImage(tempActo);
    img2.Caption = Paragraph('24-hour rhythmic patterns across multiple days.');
    img2.Caption.Bold = true; img2.Caption.FontSize = '12pt';
    add(sect1, img2);
    tempFiles{end+1} = tempActo;

    % 2. Sleep Summary
    add(sect1, Section('Title', 'Sleep Summary Metrics'));
    if isfield(this.SleepSummary, 'Report') && ~isempty(this.SleepSummary.Report)
        rep = this.SleepSummary.Report;
        data = {
            'Total Sleep (h)',      num2str(round(rep.total_sleep_h,2));
            'Primary Sleep Onset',  char(string(rep.primary_onset));
            'Primary Sleep Offset', char(string(rep.primary_offset));
            'Primary Sleep (h)',    num2str(round(rep.primary_sleep_h,2));
            'WASO (min)',           num2str(round(rep.waso_min,1));
            'Nap (h/day)',          num2str(round(rep.nap_h,2));
            'Nap times/day',        num2str(round(rep.nap_times,1))
        };
        add(sect1, createStandardTable({'Metric', 'Value'}, data));
    else
        add(sect1, 'No sleep data available.');
    end
    add(doc, sect1);

    % --- Section 2: Circadian & Non-parametric Analysis ---
    sect2 = Chapter('Title', 'Circadian & Non-parametric Analysis');

    % Clock Plot
    add(sect2, Section('Title', 'Cosinor Clock Plot'));
    hf = figure('Color', 'w', 'Visible', 'off');
    ha = axes(hf, 'Units', 'normalized', 'Position', [.1 .1 .8 .8]);
    if isfield(this.CosinorInfo, 'UserData') && isa(this.CosinorInfo.UserData, 'cosinor')
        this.CosinorInfo.UserData.plot(ha);
    end
    tempClock = [tempname '.svg'];
    exportgraphics(hf, tempClock, 'ContentType', 'vector');
    close(hf);
    img3 = FormalImage(tempClock);
    img3.Height = '5in';
    img3.Caption = Paragraph('Clock representation of rhythm phase and amplitude.');
    img3.Caption.Bold = true; img3.Caption.FontSize = '12pt';
    add(sect2, img3);
    tempFiles{end+1} = tempClock;

    % 1. Cosinor Summary
    add(sect2, Section('Title', 'Cosinor Rhythms Detailed Summary'));
    if ~isempty(this.CosinorSummary)
        sumT = this.CosinorSummary;

        base = {'Mean Act', 'Std Act', 'MESOR', 'MESOR LB', 'MESOR UB', 'P-val', 'R²'};
        periods = extractAfter(sumT.Properties.VariableNames(contains(sumT.Properties.VariableNames,'amplitude_lb_')),'amplitude_lb_');
        human = base;
        for iP = 1:numel(periods)
            per = periods{iP};
            human = [human {['Amp ' per], ['Amp LB ' per], ['Amp UB ' per], ...
                ['Phase (°) ' per], ['Phase (°) LB ' per], ['Phase (°) UB ' per], ...
                ['Phase (h) ' per], ['Phase (h) LB ' per], ['Phase (h) UB ' per]}];
        end
        vals = round(table2array(sumT),2);
        cosVals = cell(size(vals));
        cols = sumT.Properties.VariableNames;
        for jC = 1:length(cols)
            if contains(cols{jC}, '_in_hour')
                v = vals(jC);
                cosVals{jC} = formatHourToTime(v);
            else
                cosVals{jC} = num2str(vals(jC));
            end
        end
        cosData = [human(1:length(cosVals))' cosVals'];
        add(sect2, createStandardTable({'Parameter', 'Value'}, cosData));
    else
        add(sect2, 'No cosinor data available.');
    end

    % 2. IS/IV Summary (MOVED HERE)
    add(sect2, Section('Title', 'Inter-daily Stability & Intra-daily Variability'));
    if isfield(this.ISIVSummary, 'Report') && ~isempty(this.ISIVSummary.Report)
        labels = {'IS', 'IV', 'Period (h)', '% Missing Data', '% Missing Bin', 'Timescale'};
        vals = round(table2array(this.ISIVSummary.Report), 2);
        data = [labels' arrayfun(@num2str, vals', 'UniformOutput', false)];
        add(sect2, createStandardTable({'Metric', 'Value'}, data));
    else
        add(sect2, 'No IS/IV data available.');
    end

    % 3. M10/L5 Summary (MOVED HERE)
    add(sect2, Section('Title', 'M10 & L5 Non-parametric Analysis'));
    if ~isempty(this.M10L5Summary)
        vals = table2array(this.M10L5Summary);
        data = {
            'Relative Amplitude (RA)', num2str(round(vals(1),2));
            'M10 (Avg Activity)',      num2str(round(vals(2),2));
            'M10 Midpoint',            formatHourToTime(vals(3));
            'L5 (Avg Activity)',       num2str(round(vals(4),2));
            'L5 Midpoint',             formatHourToTime(vals(5))
        };
        add(sect2, createStandardTable({'Metric', 'Value'}, data));
    else
        add(sect2, 'No M10/L5 data available.');
    end

    add(doc, sect2);

    close(doc);

    movefile(tempPDF, outputPath, 'f');

    this.message.content = ['Multi-page report generated: ' outputPath];
    this.message.type    = 'success';

    % Cleanup
    for iP = 1:length(tempFiles)
        if exist(tempFiles{iP}, 'file'), delete(tempFiles{iP}); end
    end

catch ME
    this.message.content = 'Report cannot be generated!';
    this.message.type    = 'error';
    if isvalid(doc), close(doc); end
    rethrow(ME);
end
end

% --- HELPER: Create Consistent Professional Table ---
function tbl = createStandardTable(headers, data)
    import mlreportgen.dom.*;
    tbl = FormalTable(headers, data);

    tbl.Style = {Width('85%'), Border('solid', 'black', '1pt')};

    % Header Styling
    tbl.Header.Style = {BackgroundColor('lightgray'), Bold(true)};

    % Fixed Column Alignment (40/60 split)
    gr = TableColSpecGroup;
    c1 = TableColSpec; c1.Style = {Width('40%')};
    c2 = TableColSpec; c2.Style = {Width('60%')};
    gr.ColSpecs = [c1 c2];
    tbl.ColSpecGroups = gr;

    tbl.TableEntriesStyle = {InnerMargin('4pt','4pt','3pt','3pt'), VAlign('middle')};
end

% --- HELPER: Time Formatting ---
function timeStr = formatHourToTime(hVal)
    hh = floor(hVal);
    mm = floor((hVal - hh) * 60);
    ss = round(((hVal - hh) * 60 - mm) * 60);
    if ss == 60, ss = 0; mm = mm + 1; end
    if mm == 60, mm = 0; hh = hh + 1; end
    timeStr = sprintf('%02d:%02d:%02d', hh, mm, ss);
end